# Generated by Django 4.1.5 on 2023-02-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.state')),
            ],
            options={
                'db_table': 'lawyer',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
