# Generated by Django 4.1.5 on 2023-02-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('fir_copy', models.CharField(max_length=255)),
                ('police_station', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=50)),
                ('case_reg_date', models.DateField()),
                ('court', models.CharField(max_length=50)),
                ('judge', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.lawyer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.state')),
            ],
            options={
                'db_table': 'cases',
            },
        ),
    ]
