# Generated by Django 4.1.5 on 2023-02-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0005_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.cases')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.client')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
