# Generated by Django 4.1.5 on 2023-02-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
