# Generated by Django 4.1.5 on 2023-02-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0009_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('rating', models.IntegerField()),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.cases')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.client')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.lawyer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
