# Generated by Django 4.1.5 on 2023-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
