# Generated by Django 4.1.5 on 2023-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
