# Generated by Django 5.0 on 2024-03-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0023_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminlawyer.client')),
            ],
            options={
                'db_table': 'contact_client',
            },
        ),
    ]
