# Generated by Django 5.0 on 2024-04-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0024_contact_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_client',
            name='client',
        ),
    ]
